### ISSUE TITLE
Basic Splitting Strategies

### ISSUE THREAD

**Issue by abstractqqq** [abstractqqq/dsds#8]
We should provide basic splitting strategies.
1. Train test split for Polars.
2. Recent split by sort column.
3. Support for 3,4 splits at once.
4. An alternative to provide a split_index column instead of actually splitting the dataframe. The split_index will contain unique identifiers to the 3 or 4 splits.

**Comment by ion-elgreco** [comment]
> We should provide basic splitting strategies.
> 1. Train test split for Polars.
> 2. Recent split by sort column.
> 3. Support for 3,4 splits at once.
> 4. An alternative to provide a split_index column instead of actually splitting the dataframe. The split_index will contain unique identifiers to the 3 or 4 splits. 

Timeseries split could also be useful, btw I like the package! Hopefully you can have a docs page soon

**Comment by abstractqqq** [comment]
> There is functime if you are not aware. Their design principles are a bit different from mine, but they primarily focus on time series.

https://github.com/descendant-ai/functime

**Comment by ion-elgreco** [comment]
> > Timeseries split could also be useful
> 
> There is functime if you are not aware. Their design principles are a bit different from mine, but they primarily focus on time series.
> 
> https://github.com/descendant-ai/functime

I am aware of it. Their package however assumes data to be formatted in a specific in terms of sorting and the order of columns which makes it extremely inflexible.

**Comment by abstractqqq** [comment]
> > > Timeseries split could also be useful
> > 
> > 
> > There is functime if you are not aware. Their design principles are a bit different from mine, but they primarily focus on time series.
> > https://github.com/descendant-ai/functime
> 
> I am aware of it. Their package however assumes data to be formatted in a specific way in terms of sorting and the order of columns which makes it extremely inflexible.

I see. I don't work with time series that often so if you can provide some articles for me to read through that will be very helpful! I remember doing some splitting, where train is all up to certain month say X, and test is X+1, X + 2, X+3 months, and keeps rolling X. Not sure if this is what you are looking for.

**Comment by abstractqqq** [comment]
> > > Timeseries split could also be useful
> > 
> > 
> > There is functime if you are not aware. Their design principles are a bit different from mine, but they primarily focus on time series.
> > https://github.com/descendant-ai/functime
> 
> I am aware of it. Their package however assumes data to be formatted in a specific way in terms of sorting and the order of columns which makes it extremely inflexible.

I added time_series_split in the commit: 58e13b1
The behavior is the same as the sklearn one. I haven't tested for performance. It is part of dsds.sample.
Feel free to take a look! I am planning to update the package this weekend, and this will be part of 0.0.25.

**Comment by abstractqqq** [comment]
The update got delayed because I integrated Rust into the new NLP initiative.. Need some time to make sure it packages correctly.
